os: osx
language: objective-c
osx_image: xcode9.2
git:
  submodules: false
cache: false
before_install:
  - gem install cocoapods -v '1.3.1'
  - brew install carthage
  - git submodule update --init
  - pod install
  - carthage update
  - ./ci/scripts/versions.sh
before_script:
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/certs/potatso-development.cer.enc -d -a -out ci/certs/potatso-development.cer
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/certs/potatso-development.p12.enc -d -a -out ci/certs/potatso-development.p12
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/main-development.mobileprovision.enc -d -a -out ci/profiles/main-development.mobileprovision
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/ex-packettunnel-development.mobileprovision.enc -d -a -out ci/profiles/ex-packettunnel-development.mobileprovision
  - openssl aes-256-cbc -k "$CERTS_PASSWORD" -in ci/profiles/ex-todaywidget-development.mobileprovision.enc -d -a -out ci/profiles/ex-todaywidget-development.mobileprovision
  - ./ci/scripts/add_key.sh
  - ./ci/scripts/install_profiles.sh
script:
  - while sleep 540s; do echo "=== still running ($SECONDS seconds) ==="; done &  # peridiocally print something to console to trick Travis that build process is still running (10m is cut-out time for travis)
  - xcodebuild -workspace Potatso.xcworkspace -scheme Potatso -configuration "$XCODEBUILD_CONFIGURATION" -sdk "$XCODEBUILD_SDK" -arch arm64 > /dev/null
  - jobs -p # print out all job number
  - kill -9 `jobs -p` # kill all jobs in this shell
after_success:
  - jobs -p # print out all job number
  - kill -9 `jobs -p`
after_failure:
  - jobs -p # print out all job number
  - kill -9 `jobs -p`